version: '2'

services:
  db:
    image: postgres
    volumes: 
      - ./postgres:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: dankogai
      POSTGRES_PASSWORD: kogaidan
  fastladder:
    image: ssig33/fastladder-postgres
    depends_on:
      - db
    links:
      - db
    ports:
      - 8080:5000
    restart: always
    environment:
      DATABASE_URL: postgres://dankogai:kogaidan@db/fastladder
      RAILS_ENV: production
      SECRET_KEY_BASE: "PLEASE CHANGE THIS"
